// Runtime config injected by static/config.js (regenerated by main.py at
// every service start; public/config.js is the dev fallback).

import type { HmiConfig } from './api';

declare global {
  interface Window {
    HMI_CONFIG?: HmiConfig;
  }
}

export {};
