# config/mosquitto/mosquitto.conf

# ============================================
# MOSQUITTO CONFIGURATION - DEVELOPMENT MODE
# ============================================

# Listener configuration
listener 1883
protocol mqtt

# WebSocket listener
listener 9001
protocol websockets

# FOR TESTING PURPOSES ONLY 
allow_anonymous true

# Persistencia de mensajes
persistence true
persistence_location /mosquitto/data/

# log files
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# logs format
log_timestamp true
log_timestamp_format %Y-%m-%d %H:%M:%S

# QoS y mensajes retenidos
max_queued_messages 1000
message_size_limit 10485760  # 10MB (audio)

# number clients connected
max_connections -1

# time no activity before disconnect a client (s)
max_keepalive 3600

# statistcs of each topics (s)
sys_interval 15