import { resolve } from 'node:path';
import { defineConfig } from 'vite';

// Builds straight into the FastAPI static dir. `emptyOutDir` is safe:
// everything in static/ is build output, and config.js is regenerated by
// main.py at every service start (public/config.js is only a dev fallback).
export default defineConfig({
  build: {
    outDir: '../static',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        index: resolve(__dirname, 'index.html'),
        setup: resolve(__dirname, 'setup.html'),
      },
    },
  },
  server: {
    proxy: {
      // Everything under /api goes to the FastAPI service; ws:true is
      // required for /api/v1/plugin/chat/stream.
      '/api': {
        target: 'http://localhost:8005',
        ws: true,
      },
    },
  },
});
